<? $this->displayPanel('buildingsbox'); ?>
<br class="clear" />
<? $this->displayPanel('technologiesbox'); ?>
<br class="clear" />
<? $this->displayPanel('unitsbox'); ?>
<br class="clear" />
<? $this->displayPanel('lostbuildings'); ?>
<br class="clear" />
<? $this->displayPanel('buildingevents'); ?>