Aufgrund vulkanischer Aktivitäten haben sich die Kontinentalplatten Rakuuns verschoben!
Die Oberfläche des Planeten wurde in einen westlichen und einen östlichen Kontinenten gespalten...
Die neuen geografischen Begebenheiten führten zur Auflösung der alten politischen Strukturen.
Auf dem westlichen Kontinenten hat sich die Bevölkerung zu einer großen Allianz zusammengeschlossen, die sich "Black" nennt, während gleichzeitig auf dem östlichen Kontinent die Allianz "White" entstanden ist...